name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, safari, allBrowser]
        device: ["iphone12ProMax","Pixel5","iPadPro11","desktop"]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16


    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run the Test Script
      id: test
      run: npm run test:${{ matrix.browser }}:${{ matrix.device }} -- --reporter=json
      
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.browser }}-${{ matrix.device }}
        path: playwright-report/
